# Generated by Django 5.0.4 on 2024-05-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_generate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codemodel',
            name='data',
            field=models.CharField(max_length=290, null=True, unique=True),
        ),
    ]
